rules:
  - id: no-fractional-cpu-limits
    patterns:
      - pattern-inside: |
          limits:
            ...
      - pattern: |
          cpu: $CPU_LIMIT
      - metavariable-regex:
          metavariable: $CPU_LIMIT
          regex: \d{0,3}m
    fix: "cpu: 1000m"
    message: "no-fractional-cpu-limits 잠재적 결함 및 보안 이격율 정비 요망."
    severity: WARNING
    languages: [yaml]
    metadata:
      category: best-practice
      technology:
        - kubernetes
