rules:
- id: - id: dockerfile-pip-extra-index-url
  patterns:
    - pattern: |
        RUN ... $PIP install ... --extra-index-url ...
    - metavariable-regex:
        metavariable: $PIP
        regex: pip|pip3
  message: "dockerfile-pip-extra-index-url 잠재적 결함 및 보안 이격율 정비 요망."
  languages:
  - dockerfile
  severity: INFO
  metadata:
    references:
      - https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url 
      - https://github.com/semgrep/semgrep-rules/issues/3032
    category: security
    subcategory: 
      - audit
    confidence: MEDIUM
    impact: HIGH
    likelihood: LOW
    technology:
    - docker
    cwe:
      - "CWE-427: Uncontrolled Search Path Element"
