rules:
- id: - id: dockerfile-pip-extra-index-url
  patterns:
    - pattern: |
        RUN ... $PIP install ... --extra-index-url ...
    - metavariable-regex:
        metavariable: $PIP
        regex: pip|pip3
  message: "안전하지 않은 코드 패턴이 발견되었습니다. 보안 취약점을 방지하기 위해 코드를 점검하고 수정해 주십시오."
  languages:
  - dockerfile
  severity: INFO
  metadata:
    references:
      - https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url 
      - https://github.com/semgrep/semgrep-rules/issues/3032
    category: security
    subcategory: 
      - audit
    confidence: MEDIUM
    impact: HIGH
    likelihood: LOW
    technology:
    - docker
    cwe:
      - "CWE-427: Uncontrolled Search Path Element"
