rules:
- fix-regex:
    regex: development
    replacement: dev
  id: flask-debugging-enabled
  languages:
  - yaml
  message: 설정(YAML) 파이프라인 및 가변 인젝션 옵션 단속 점검.
  metadata:
    category: security
    confidence: LOW
    cwe:
    - 'CWE-489: Active Debug Code'
    impact: MEDIUM
    likelihood: LOW
    owasp: A06:2017 - Security Misconfiguration
    references:
    - https://flask.palletsprojects.com/en/2.0.x/debugging/
    - https://flask.palletsprojects.com/en/2.0.x/config/#ENV
    subcategory:
    - audit
    technology:
    - kubernetes
    - flask
  patterns:
  - pattern-inside: 'env: [...]

      '
  - pattern: '{name: FLASK_ENV, value: "development"}

      '
  severity: WARNING
